const body = document.body
const siteLogo = document.querySelector(".site-logo")
const darkMode = document.querySelector(".dark-mode")
const lightMode = document.querySelector(".light-mode")
const dark = document.querySelector(".dark")
const mode = document.querySelector(".mode")
const searchBlock = document.querySelector(".search-block")
const searchPlaceholder = document.querySelector(".search-placeholder")
const user = document.querySelector(".user-info")
const name = document.querySelector(".name")
const lastJoin = document.querySelector(".last-join")
const userAccauntInfo = document.querySelector(".user-accaunt-info")
const blockTitle = document.querySelector(".block-title")
const followersTitle = document.querySelector(".followers-title")
const followingTitle = document.querySelector(".following-title")
const blockNumber = document.querySelector(".block-number")
const followersNumber = document.querySelector(".followers-number")
const followingNumber = document.querySelector(".following-number")
const linkIcon = document.querySelector(".link-icon")
const linkText = document.querySelector(".link-text")
const twitterIcon = document.querySelector(".twitter-icon")
const twitterText = document.querySelector(".twitter-text")
const sun = document.querySelector(".sun")
const moon = document.querySelector(".moon")

darkMode.addEventListener("click", ()=>{
    body.style.backgroundColor = "#141D2F"
        siteLogo.style.color = "#FFFFFF"
        dark.style.color = "#FFFFFF"
        dark.textContent = "LIGHT"
        moon.style.display = "none"
        sun.style.display = "block"
        searchBlock.style.backgroundColor = "#1E2A47"
        searchPlaceholder.style.color = "#FFFFFF"
        user.style.backgroundColor = "#1E2A47"
        name.style.color = "#FFFFFF"
        lastJoin.style.color = "#ffffff"
        userAccauntInfo.style.backgroundColor = "#141D2F"
        blockTitle.style.color = "#FFFFFF"
        blockNumber.style.color = "#FFFFFF"
        followersNumber.style.color = "#FFFFFF"
        followersTitle.style.color = "#FFFFFF"
        followingTitle.style.color = "#FFFFFF"
        followingNumber.style.color = "#FFFFFF"
        darkMode.style.display = "none"
        lightMode.style.display = "flex"
        
})
lightMode.addEventListener("click", ()=> {
    body.style.backgroundColor = "#F6F8FF"
    siteLogo.style.color = "#222731"
    dark.style.color = "#697C9A"
    dark.textContent = "DARK"
    moon.style.display = "block"
    sun.style.display = "none"
    searchBlock.style.backgroundColor = "#FEFEFE"
    searchPlaceholder.style.color = "#4B6A9B"
    user.style.backgroundColor = "#FEFEFE"
    name.style.color = "#2B3442"
    lastJoin.style.color = "#697C9A"
    userAccauntInfo.style.backgroundColor = "#F6F8FF"
    blockTitle.style.color = "#4B6A9B"
    blockNumber.style.color = "#2B3442"
    followersNumber.style.color = "#2B3442"
    followersTitle.style.color = "#4B6A9B"
    followingTitle.style.color = "#4B6A9B"
    followingNumber.style.color = "#2B3442"
    darkMode.style.display = "flex"
    lightMode.style.display = "none"
})